# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _scattering
else:
    import _scattering

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _scattering.delete_SwigPyIterator

    def value(self):
        return _scattering.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _scattering.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _scattering.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _scattering.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _scattering.SwigPyIterator_equal(self, x)

    def copy(self):
        return _scattering.SwigPyIterator_copy(self)

    def next(self):
        return _scattering.SwigPyIterator_next(self)

    def __next__(self):
        return _scattering.SwigPyIterator___next__(self)

    def previous(self):
        return _scattering.SwigPyIterator_previous(self)

    def advance(self, n):
        return _scattering.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _scattering.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _scattering.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _scattering.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _scattering.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _scattering.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _scattering.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _scattering:
_scattering.SwigPyIterator_swigregister(SwigPyIterator)
class pair_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _scattering.pair_double_swiginit(self, _scattering.new_pair_double(*args))
    first = property(_scattering.pair_double_first_get, _scattering.pair_double_first_set)
    second = property(_scattering.pair_double_second_get, _scattering.pair_double_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _scattering.delete_pair_double

# Register pair_double in _scattering:
_scattering.pair_double_swigregister(pair_double)
class trajectory(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _scattering.trajectory_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _scattering.trajectory___nonzero__(self)

    def __bool__(self):
        return _scattering.trajectory___bool__(self)

    def __len__(self):
        return _scattering.trajectory___len__(self)

    def __getslice__(self, i, j):
        return _scattering.trajectory___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _scattering.trajectory___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _scattering.trajectory___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _scattering.trajectory___delitem__(self, *args)

    def __getitem__(self, *args):
        return _scattering.trajectory___getitem__(self, *args)

    def __setitem__(self, *args):
        return _scattering.trajectory___setitem__(self, *args)

    def pop(self):
        return _scattering.trajectory_pop(self)

    def append(self, x):
        return _scattering.trajectory_append(self, x)

    def empty(self):
        return _scattering.trajectory_empty(self)

    def size(self):
        return _scattering.trajectory_size(self)

    def swap(self, v):
        return _scattering.trajectory_swap(self, v)

    def begin(self):
        return _scattering.trajectory_begin(self)

    def end(self):
        return _scattering.trajectory_end(self)

    def rbegin(self):
        return _scattering.trajectory_rbegin(self)

    def rend(self):
        return _scattering.trajectory_rend(self)

    def clear(self):
        return _scattering.trajectory_clear(self)

    def get_allocator(self):
        return _scattering.trajectory_get_allocator(self)

    def pop_back(self):
        return _scattering.trajectory_pop_back(self)

    def erase(self, *args):
        return _scattering.trajectory_erase(self, *args)

    def __init__(self, *args):
        _scattering.trajectory_swiginit(self, _scattering.new_trajectory(*args))

    def push_back(self, x):
        return _scattering.trajectory_push_back(self, x)

    def front(self):
        return _scattering.trajectory_front(self)

    def back(self):
        return _scattering.trajectory_back(self)

    def assign(self, n, x):
        return _scattering.trajectory_assign(self, n, x)

    def resize(self, *args):
        return _scattering.trajectory_resize(self, *args)

    def insert(self, *args):
        return _scattering.trajectory_insert(self, *args)

    def reserve(self, n):
        return _scattering.trajectory_reserve(self, n)

    def capacity(self):
        return _scattering.trajectory_capacity(self)
    __swig_destroy__ = _scattering.delete_trajectory

# Register trajectory in _scattering:
_scattering.trajectory_swigregister(trajectory)
class lennard_jones(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, V0, r0=1.):
        _scattering.lennard_jones_swiginit(self, _scattering.new_lennard_jones(V0, r0))

    def __call__(self, r):
        return _scattering.lennard_jones___call__(self, r)

    def V0(self):
        return _scattering.lennard_jones_V0(self)

    def r0(self):
        return _scattering.lennard_jones_r0(self)
    __swig_destroy__ = _scattering.delete_lennard_jones

# Register lennard_jones in _scattering:
_scattering.lennard_jones_swigregister(lennard_jones)
class hard_sphere_potential(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, V0, r0=1.0):
        _scattering.hard_sphere_potential_swiginit(self, _scattering.new_hard_sphere_potential(V0, r0))

    def __call__(self, r):
        return _scattering.hard_sphere_potential___call__(self, r)

    def V0(self):
        return _scattering.hard_sphere_potential_V0(self)

    def r0(self):
        return _scattering.hard_sphere_potential_r0(self)
    __swig_destroy__ = _scattering.delete_hard_sphere_potential

# Register hard_sphere_potential in _scattering:
_scattering.hard_sphere_potential_swigregister(hard_sphere_potential)
class inverse_square(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, V0):
        _scattering.inverse_square_swiginit(self, _scattering.new_inverse_square(V0))

    def __call__(self, r):
        return _scattering.inverse_square___call__(self, r)

    def V0(self):
        return _scattering.inverse_square_V0(self)
    __swig_destroy__ = _scattering.delete_inverse_square

# Register inverse_square in _scattering:
_scattering.inverse_square_swigregister(inverse_square)
class CrossSection_hard_sphere_potential(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, V, E, b, r_max, steps):
        _scattering.CrossSection_hard_sphere_potential_swiginit(self, _scattering.new_CrossSection_hard_sphere_potential(V, E, b, r_max, steps))

    def get_trajectory(self):
        return _scattering.CrossSection_hard_sphere_potential_get_trajectory(self)

    def calculate_trajectory(self):
        return _scattering.CrossSection_hard_sphere_potential_calculate_trajectory(self)
    __swig_destroy__ = _scattering.delete_CrossSection_hard_sphere_potential

# Register CrossSection_hard_sphere_potential in _scattering:
_scattering.CrossSection_hard_sphere_potential_swigregister(CrossSection_hard_sphere_potential)
class CrossSection_lennard_jones(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, V, E, b, r_max, steps):
        _scattering.CrossSection_lennard_jones_swiginit(self, _scattering.new_CrossSection_lennard_jones(V, E, b, r_max, steps))

    def get_trajectory(self):
        return _scattering.CrossSection_lennard_jones_get_trajectory(self)

    def calculate_trajectory(self):
        return _scattering.CrossSection_lennard_jones_calculate_trajectory(self)
    __swig_destroy__ = _scattering.delete_CrossSection_lennard_jones

# Register CrossSection_lennard_jones in _scattering:
_scattering.CrossSection_lennard_jones_swigregister(CrossSection_lennard_jones)
class CrossSection_inverse_square(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, V, E, b, r_max, steps):
        _scattering.CrossSection_inverse_square_swiginit(self, _scattering.new_CrossSection_inverse_square(V, E, b, r_max, steps))

    def get_trajectory(self):
        return _scattering.CrossSection_inverse_square_get_trajectory(self)

    def calculate_trajectory(self):
        return _scattering.CrossSection_inverse_square_calculate_trajectory(self)
    __swig_destroy__ = _scattering.delete_CrossSection_inverse_square

# Register CrossSection_inverse_square in _scattering:
_scattering.CrossSection_inverse_square_swigregister(CrossSection_inverse_square)

