test_inheritance: Point.cc Point.h Point3d.cc Point3d.h test_inheritance.cc
	g++ -std=c++11 -o test_inheritance Point.cc Point3d.cc test_inheritance.cc -I.

all: test_inheritance

clean:
	rm -f *.o *~ test_inheritance
