// template_error.cc
//
// Demonstrates a genuinely awful template error message -- without any
// std::cout noise mixed in.
//
// Why avoid cout: std::cout's operator<< is itself a template with many
// overloads. If you write `std::cout << squared(p)` and squared(p) fails,
// the compiler *also* dumps every operator<< overload it considered for
// std::ostream, which drowns out the actual problem. Keeping the failing
// call as its own statement (or using std::sort, as below) keeps the
// error focused on the template that's actually broken.
//
// Two versions are included:
//   1. squared() on a type with no operator*   -- a short, readable error.
//   2. std::sort() on a type with no operator< -- the "wall of text" kind,
//      because std::sort is itself built from several layers of templates
//      (introsort -> insertion sort -> heap select -> comparator functors),
//      and gcc reports the failure at every layer.
//
// Generated by Claude Sonnet 5

#include <algorithm>
#include <iostream>
#include <vector>

template<class T>
T squared(T x) {
  return x * x;
}

// A simple struct with neither operator* nor operator< defined.
struct Point {
  double x, y;
};

int main(void) {

  int i = 5;
  std::cout << "squared(" << i << ") = " << squared(i) << std::endl;

  Point p{1.0, 2.0};
  std::vector<Point> pts = { {1.0, 2.0}, {3.0, 1.0}, {0.5, 0.5} };

  // Uncomment ONE of these at a time to see its error:

  // (1) short error: no operator* for Point
  //squared(p);

  // (2) horrible error: no operator< for Point, discovered deep inside
  //     std::sort's internals
  std::sort(pts.begin(), pts.end());

  return 0;
}
