// template_simple.cc
//
// A minimal, single-file template example.
// Compiles and runs standalone -- no headers to split, no linker issues.
// Companion to the multi-file example in CompPhys/ReviewCpp/TemplateExamples/.
// Generated by Claude Sonnet 5

#include <iostream>

// A single template function definition. The compiler does NOT compile this
// directly -- it waits until it sees squared() called with a specific type,
// then generates ("instantiates") a real function for that type.
template<class T>
T squared(T x) {
  return x * x;
}

int main(void) {

  int    i = 5;
  float  f = 2.5;
  double d = 3.14159;

  // Each of these calls causes the compiler to instantiate a *different*
  // version of squared(), even though we only wrote the function once:
  //   squared<int>(int)
  //   squared<float>(float)
  //   squared<double>(double)
  std::cout << "squared(" << i << ") = " << squared(i) << std::endl;
  std::cout << "squared(" << f << ") = " << squared(f) << std::endl;
  std::cout << "squared(" << d << ") = " << squared(d) << std::endl;

  // You can also force a specific instantiation explicitly:
  std::cout << "squared<double>(" << i << ") = "
            << squared<double>(i) << std::endl;

  return 0;
}